In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

In [2]:

np.__version__

'1.19.5'

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[2:5]

array([3, 4, 5])

In [5]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [6]:

a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
a[-1]

10

In [8]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [9]:
a[-5:-1]

array([6, 7, 8, 9])

In [10]:
np.size(a)

10

In [11]:
np.shape(a)

(10,)

In [12]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[0,0]

1

In [15]:
a[1,:]

array([4, 5, 6])

In [16]:
a[:,-1]


array([3, 6, 9])

In [17]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [19]:
np.size(a,0)

4

In [20]:
np.ndim(a)

2

In [21]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [22]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [25]:
c = np.zeros((5,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:

d = np.ones((10))
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
e = np.full((3,3),8)
e

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [29]:
f = np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [36]:
np.round(np.random.rand()*10)

2.0

In [37]:
np.random.randint(5)

1

In [49]:

np.round(np.random.rand(5,5))

array([[1., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [52]:
#EX2
Ex_matrix = np.random.rand(10,5) 
Ex_matrix[:,4] = np.round(np.random.rand(1,10))
Ex_matrix

array([[0.47067947, 0.1091246 , 0.40300671, 0.26969662, 1.        ],
       [0.86605192, 0.23474809, 0.9269567 , 0.71270041, 0.        ],
       [0.99854425, 0.7373087 , 0.04677575, 0.1487662 , 0.        ],
       [0.64507355, 0.60449514, 0.93801013, 0.39624022, 1.        ],
       [0.41093187, 0.36011761, 0.7708351 , 0.51907792, 0.        ],
       [0.67663561, 0.69680414, 0.0381466 , 0.48955256, 0.        ],
       [0.32115512, 0.70143416, 0.33438007, 0.24721589, 0.        ],
       [0.30359611, 0.32707269, 0.32899511, 0.59956631, 0.        ],
       [0.98733719, 0.15839549, 0.88653302, 0.8270871 , 1.        ],
       [0.33509364, 0.88455934, 0.16725925, 0.62324675, 0.        ]])

In [40]:
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

array([278, 328, 561, 419, 195, 386, 211, 102, 245, 133, 130, 531, 553,
       848, 713, 822, 163, 315,  26, 209, 590, 510, 329, 213, 467, 514,
       344, 292, 565, 614, 902, 679, 686, 712,   9, 844, 473, 108, 630,
       865, 487, 382, 602, 466,   6, 706, 617, 836, 976, 184,  18,  45,
       196, 922, 598, 542, 203, 241, 500, 493, 450, 949, 307, 917, 985,
        70, 954, 334, 459, 677, 642, 193, 401, 981, 502, 935, 352, 512,
       923, 543, 735, 392, 743, 785, 753, 595, 210, 816, 920, 856, 151,
       286, 236, 884, 994,  25, 273, 660, 652, 826])

In [53]:
#Ex3
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:]

array([0, 1, 0, 0, 1])

In [42]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 2, 0, 2, 0],
       [1, 0, 2, 2, 0],
       [1, 0, 0, 0, 2],
       [1, 1, 1, 0, 0],
       [2, 1, 0, 2, 2]])

In [43]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 0), (0, 1), (0, 3), (1, 2), (1, 3), (2, 4), (4, 0), (4, 3), (4, 4)]

In [44]:
rng= np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [55]:

#Ex4
rng = np.random.RandomState(123)
matrix = rng.randint(10 ,size=(10,5))
matrix

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3],
       [4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7],
       [2, 4, 8, 0, 7],
       [9, 3, 4, 6, 1],
       [5, 6, 2, 1, 8],
       [3, 5, 0, 2, 6],
       [2, 4, 4, 6, 3]])

In [46]:
rng = np.random.RandomState(777)
vertor = rng.randint(2, size=10)
vertor

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [47]:

matrix[np.where(vertor==0)]

array([[5, 7, 1, 7, 2],
       [7, 4, 4, 0, 9]])

In [48]:
matrix[np.where(vertor==1)]

array([[7, 6, 7, 1, 7],
       [4, 7, 9, 8, 7],
       [2, 0, 1, 2, 4],
       [2, 7, 4, 8, 6],
       [2, 7, 8, 0, 8],
       [3, 2, 0, 3, 3],
       [4, 0, 6, 5, 7],
       [5, 5, 8, 1, 4]])